### ISSUE TITLE
V1.2.3Version cannot generate images

### ISSUE THREAD

**Issue by Soaraz** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#251]
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/127572525/24bdf7f7-5023-40a5-bbfa-2fb4773fd6c2)

V1.2.3Version cannot generate images After clicking "Generate more Txt2mg", the session folder is empty and no images are generated. Install back to version 1.2.2 to output images normally

The installation file is Auto.Photoshop.SD.plugin_v1.2.3.CCX

**Comment by wuyue0509** [comment]
same here

**Comment by 501ZHY** [comment]
Same  Here. With --api in command and api log shows it sends request to remote machine

**Comment by eienatsu** [comment]
Same. Tried installing both PS and SD as well.

**Comment by AbdullahAlfaraj** [comment]
I've done some investigation and it seems that the issue may be caused by one of the following:
1) The ControlNet extension is not installed or not enabled.
2) The Multi ControlNet max unit is less than 3.

To fix this issue, make sure that the ControlNet extension is enabled from Auto1111 and set the max ControlNet unit to 3 or higher. 

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/dfbee8d4-5e17-473d-9462-3f658bc0f763)

Another option is to turn off the ControlNet feature from the plugin.

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/d6aadbaa-84ef-4aff-90aa-ab761a788d33)

Both of these issues will be fixed in the next update.

**Comment by wuyue0509** [comment]
it is working again if  set the max ControlNet unit to 3

**Comment by wuyue0509** [comment]
lora is error,
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/124325018/9987a2cd-bfe7-4af4-84ed-94f14b11f148)

**Comment by aleimu** [comment]
mark

**Comment by AbdullahAlfaraj** [comment]
> lora is error, ![image](https://user-images.githubusercontent.com/124325018/237847974-9987a2cd-bfe7-4af4-84ed-94f14b11f148.png)

@wuyue0509 
This is an Auto1111 bug. It has been fixed in the development branch, but we need to wait for it to be released in the main branch.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9979

**Comment by kikyolulu** [comment]
> I've done some investigation and it seems that the issue may be caused by one of the following:
> 
> 1. The ControlNet extension is not installed or not enabled.
> 2. The Multi ControlNet max unit is less than 3.
> 
> To fix this issue, make sure that the ControlNet extension is enabled from Auto1111 and set the max ControlNet unit to 3 or higher.
> 
> ![image](https://user-images.githubusercontent.com/7842232/237371863-dfbee8d4-5e17-473d-9462-3f658bc0f763.png)
> 
> Another option is to turn off the ControlNet feature from the plugin.
> 
> ![image](https://user-images.githubusercontent.com/7842232/237373147-d6aadbaa-84ef-4aff-90aa-ab761a788d33.png)
> 
> Both of these issues will be fixed in the next update.

Where can I find the settings to change the ControlNet unit? I tried turning off ControlNet feature from the plugin, and still getting the "the command "show" is not currently available"

**Comment by wuyue0509** [comment]
something error,
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/124325018/cc262568-4f38-4aa1-ae7c-22fe59c690cc)

**Comment by AbdullahAlfaraj** [comment]
this issue has been solved in v1.2.4

**Comment by gee666** [comment]
@AbdullahAlfaraj  Do I need to reinstall the plugin or does it update itself?

**Comment by AbdullahAlfaraj** [comment]
> @AbdullahAlfaraj Do I need to reinstall the plugin or does it update itself?

You will need to update it. 

Method 1: Just double click the new .ccx file and it will update itself
method 2: Replace the old unzipped folder with the newly one
Method 3: do ```git pull``` , similar to how you do it for Auto1111
