### ISSUE TITLE
exception:fail to read an image file

### ISSUE THREAD

**Issue by adunato** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#6]
Hello,

I'm getting an exception when trying to "Set Init Image" in img2img.
Steps:
- select img2img
- select image in layer (ctrl click on layer)
- Press "Set Init Image"

The issue seems to be in relation to the generation of the png in init_images folder as if I save it manually in such folder (same layer name) it works.

txt2img works fine.

![image](https://user-images.githubusercontent.com/7783232/208944021-9fe0783a-d140-42dc-809d-16eaae6ccbe4.png)

**Comment by WildDogOne** [comment]
I get the same problem when I use img2img or inpaint/outpaint
It feels like the plugin is not able to read the layer information from photoshop and copy it out into that directory structure

**Comment by DioVayne** [comment]
Same here. I don't see any "Layer 1 copy.png" being generated in the directory tree.

**Comment by lionrooter** [comment]
I'm getting this issue as well.

**Comment by DrMacabre** [comment]
same here, worked once then not anymore

**Comment by jeremymccurdy** [comment]
Same here when trying to inpaint or use img2img

**Comment by AbdullahAlfaraj** [comment]
This issue should be resolved in v1.0.5 check your plugin version and update accordingly.

**Comment by DioVayne** [comment]
Still not working for me. These are the logs from UXP and startserver.bat after clicking "init inpaint mask" and "generate". 

![image](https://user-images.githubusercontent.com/2700848/209469709-9a80eecd-3d8e-4773-8f8c-58f85d77825b.png)

![image](https://user-images.githubusercontent.com/2700848/209469725-7720b1fa-c771-49db-b5f3-8fcce55a49c0.png)

**Comment by AbdullahAlfaraj** [comment]
@DioVayne , the reason why you guys are getting this error, is because photoshop feature "quick export as png" will break at random. if you search the [adobe developer community forums](https://forums.creativeclouddeveloper.com/ ) you will find all kind of temporary solution.
the easiest of which is to just 
* Restart photoshop. 
* Open a project then 
* Create new layer. 
* Right click the layer and select quick export as png.
* If you get prompted with an export window. it means the feature is working.
close the export window without exporting and start using the plugin. 
everything should work fine.

**Comment by paulsnoops** [comment]
@AbdullahAlfaraj I have tried your suggested fix here and the right click > export shows an export window fine every time after a restart but as soon as I inititate a mask for in/outpainting I get this same error and right click stops working at that point

**Comment by Astenru** [comment]
I have the same problem after the first launch "Init outpage Mask"
If you select Export AS in Photoshop, then the screen shows such a screen with errors.
![image_7189](https://user-images.githubusercontent.com/121602986/209919857-050ad292-bc4d-4bd8-8f04-225b877f0acc.png)

**Comment by AbdullahAlfaraj** [comment]
today's update #42 should fix the issue, please let me know if anything else comes up
